version: '3'
services:
  node-app:
   container_name: express-node-app
   build: .
   env_file:
   - ./.env
   ports:
   - "4000:4000"
   volumes:
   - './src:/app/src:ro'
  nginx:
   image: nginx:alpine
   ports:
   - "80:80"
   volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
   - node-app

